version: '3.8'

services:
  help-chat:
    container_name: chat-dr
    build: .
    ports:
      - "5001:5000"
    volumes:
      - ./app:/app
    environment:
      - FLASK_ENV=development
    restart: unless-stopped
